import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from "next-auth/next"

import Provider from "@/components/providers/NextAuthProvider"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import { Toaster } from 'react-hot-toast'
import Navbar from '@/components/Navbar'
import ThemeProvider from '@/components/providers/ThemeProvider'

import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  const session = await getServerSession(authOptions)



  return (
    <html lang="en" suppressHydrationWarning >
      <head />
      <body className={`${inter.className}`}  >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <Toaster
            position="top-center"
            reverseOrder={true}
          />
          <Provider session={session}>
            <Navbar />
            {children}
          </Provider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html >
  )
}
